### ISSUE TITLE
Python: can't open file 'Demuxalot.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MrLocuace** [drneavin/Demultiplexing_Doublet_Detecting_Docs#37]
Hi @drneavin ,

I am trying running the script below. I have both Demuxalot.py and Demuxalot.sif in this dir: /project/PI/USERS/me/czi/data/scrna, which is located upstream of all input files. 

#!/bin/bash

###########################################
#SBATCH --time=34:00:00
##SBATCH --partition=PI
#SBATCH --account=pi-lb
#SBATCH --mem=120G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --output=/project/PI/USERS/me/czi/data/scrna/demuxalot/demuxalot-%j.out
#SBATCH --error=/project/PI/USERS/me/czi/data/scrna/demuxalot/demuxalot-%j.err
###########################################

module load apptainer/1.1.4

cd /project/PI/USERS/me/czi/data/scrna

DIR1=/project/PI/USERS/me/czi/data/scrna
BATCH=${1}
SAMPLE=$(echo "$BATCH")
#SAMPLE=$(echo "$BATCH" | cut -d"_" -f1)

BARCODES=$DIR1/cellranger/${SAMPLE}_OUT/outs/filtered_feature_bc_matrix/barcodes.tsv
BAM=$DIR1/cellranger/${SAMPLE}_OUT/outs/possorted_genome_bam.bam
INDS=$DIR1/demuxalot/indvs_batch1.txt
VCF=$DIR1/souporcell/batch1.MAF0.05.vcf.gz
DEMUXALOT_OUTDIR=$DIR1/demuxalot/${SAMPLE}_OUT

apptainer exec --bind $DIR1:/tmp Demuxafy.sif python Demuxalot.py
-b /tmp/$BARCODES
-a /tmp/$BAM
-n /tmp/$INDS
-v /tmp/$VCF
-o /tmp/$DEMUXALOT_OUTDIR
-r True

But I get this error:

/opt/conda/envs/py37/bin/python: can't open file 'Demuxalot.py': [Errno 2] No such file or directory. I have tried modifying the script several times but all the time I get the same error.

Also, if helpful, these are the contents of the container:

[me@midway3-login3 scrna]$ apptainer exec Demuxafy.sif pwd
/home/me
[me@midway3-login3 scrna]$ apptainer exec Demuxafy.sif ls
R RtmpHkYF2q RtmpM5ugYe RtmpTi73Rg authorized_keys cellranger_count1.sbatch include perl5 thindrives
RtmpACNEOR RtmpLYUF84 RtmpMfuEoa Rtmpc673Mn bin customize_env.sh lib share

Please help

**Comment by drneavin** [comment]
Hi @MrLocuace , this is a typo on my end. It should be `apptainer exec --bind $DIR1:/tmp Demuxafy.sif Demuxalot.py` instead of `apptainer exec --bind $DIR1:/tmp Demuxafy.sif python Demuxalot.py` (ie remove the `python` from the command). It's been on my list of things to fix in the docs along with some other issues for some time so this was a good instigation to fix it. It should be updated in the docs now too.

**Comment by MrLocuace** [comment]
Hi @drneavin,
I corrected the issue. I have followed all the instructions, I just copied Demuxalot.py but it is not working. 

Also, I just tried:

apptainer exec --bind Demuxafy.sif Demuxalot.py \
        -b /project/PI/USERS/me/czi/data/scrna/cellranger/LB-CC-20s-02-LPS-GEX-b1-FC02_OUT/outs/filtered_feature_bc_matrix/barcodes.tsv \
        -a /project/PI/USERS/me/czi/data/scrna/cellranger/LB-CC-20s-02-LPS-GEX-b1-FC02_OUT/outs/possorted_genome_bam.bam \
        -n /project/PI/USERS/me/czi/data/scrna/demuxalot/indvs_batch1.txt \
        -v /project/PI/USERS/me/czi/data/scrnasouporcell/batch1.MAF0.05.vcf.gz \
        -o /project/PI/USERS/me/czi/data/scrna/demuxalot/LB-CC-20s-02-LPS-GEX-b1-FC02_OUT \
        -r True
        
But got:

FATAL:   could not open image /project/PI/USERS/me/czi/data/scrna/Demuxalot.py: image format not recognized

**Comment by drneavin** [comment]
Hi @MrLocuace , it looks like you forgot to add the path to bind so it's interpreting `Demuxafy.sif` as the path to bind and `Demuxalot.py` as the image. Try this:

```
apptainer exec --bind $DIR1:/tmp Demuxafy.sif Demuxalot.py
-b /tmp/$BARCODES
-a /tmp/$BAM
-n /tmp/$INDS
-v /tmp/$VCF
-o /tmp/$DEMUXALOT_OUTDIR
-r True
```

**Comment by MrLocuace** [comment]
@drneavin I did the change:

#!/bin/bash

###########################################
#SBATCH --time=34:00:00                                                                                                
##SBATCH --partition=PI                                                                                            
#SBATCH --account=pi-lb                                                                                       
#SBATCH --mem=120G                                                                                                                                                                                                      
#SBATCH --nodes=1                                                                                                     
#SBATCH --ntasks=1                                                                                                    
#SBATCH --cpus-per-task=12
#SBATCH --output=/project/PI/USERS/me/czi/data/scrna/demuxalot/demuxalot-%j.out
#SBATCH --error=/project/PI/USERS/me/czi/data/scrna/demuxalot/demuxalot-%j.err 
###########################################

module load apptainer/1.1.4

cd /project/lbarreiro/USERS/lucas/czi/data/scrna

DIR=/project/lbarreiro/USERS/lucas/czi/data/scrna
BATCH=${1}
SAMPLE=$(echo "$BATCH")
#SAMPLE=$(echo "$BATCH" | cut -d"_" -f1)

BARCODES=$DIR/cellranger/${SAMPLE}_OUT/outs/filtered_feature_bc_matrix/barcodes.tsv
BAM=$DIR/cellranger/${SAMPLE}_OUT/outs/possorted_genome_bam.bam
INDS=$DIR/demuxalot/indvs_batch1.txt
VCF=$DIR/souporcell/batch1.MAF0.05.GRCh38.2.vcf.gz
DEMUXALOT_OUTDIR=$DIR1/demuxalot/${SAMPLE}_OUT

apptainer exec --bind $DIR1:/tmp Demuxafy.sif Demuxalot.py \
        -b /tmp/$BARCODES \
        -a /tmp/$BAM \
        -n /tmp/$INDS \
        -v /tmp/$VCF \
        -o /tmp/$DEMUXALOT_OUTDIR \
        -r True

But I get:

Traceback (most recent call last):
  File "/opt/Demultiplexing_Doublet_Detecting_Docs/scripts/Demuxalot.py", line 26, in <module>
    with open(args.indiv_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp//project/PI/USERS/me/czi/data/scrna/demuxalot/indvs_batch1.txt'

Even after replacing: /tmp/$INDS \ by /tmp$INDS \

I get: No such file or directory: '/tmp//project/PI/USERS/me/czi/data/scrna/demuxalot/indvs_batch1.txt'

Maybe I can send you my input files by email?

Thank you very much

**Comment by drneavin** [comment]
Hmm, can you do `ls /tmp//project/PI/USERS/me/czi/data/scrna/demuxalot/indvs_batch1.txt` to check if the file exists? Also, I think the bind directories should be separated by a comma instead of a colon. I think the ":" maps the $DIR to /tmp instead of binding both. You can also do it as two different parameters to be very careful:

```
apptainer exec --bind $DIR1 --bind /tmp Demuxafy.sif Demuxalot.py
-b /tmp/$BARCODES
-a /tmp/$BAM
-n /tmp/$INDS
-v /tmp/$VCF
-o /tmp/$DEMUXALOT_OUTDIR
-r True
```

**Comment by drneavin** [comment]
Closing this due to inactivity but please reopen if it remains unresolved
